import "./globals.css";
import { Poppins } from "next/font/google";
import Navbar from "./navbar";

const poppins = Poppins({ 
  subsets: ["latin"], 
  weight: ["100", "200", "400", '500', '600', '700', '900'] 
});

export const metadata = {
    title: "t_portfo",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={poppins.className}>
              <Navbar/><br></br>
              {children}
              </body>
        </html>
    );
}
